name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-mac: 
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install pkg-config
        brew install libomp
        brew install xgboost
        cp xgboost.pc /usr/local/lib/pkgconfig/
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
