name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-mac: 
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install libomp
        pip3 install xgboost
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  test-ubuntu: 
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -f Dockerfile_test_ubuntu -t xgbswift-test .
    - name: Run tests
      run: docker run xgbswift-test