name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-ubuntu: 
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -f Dockerfile_test_ubuntu -t xgbswift-test .
    - name: Run tests
      run: docker run xgbswift-test